version: "3"
services:
  perl-fpm:
    image: perl-fpm
    build:
      context: perl-fpm/
      dockerfile: ../Dockerfile
    volumes:
      - "./www:/var/www"

  webserver:
    image: nginx:alpine
    volumes:
      - "./www:/var/www"
      - "./nginx:/etc/nginx/conf.d"
    ports:
       - "0.0.0.0:8080:80"
    links:
       - perl-fpm
